apiVersion: v1
kind: Service
metadata:
  name: {{ template "flock-api.fullname" . }}
  labels:
    app: {{ template "flock-api.name" . }}
    chart: {{ template "flock-api.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    prometheus.io/scrape: "\"true\""
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "flock-api.name" . }}
    release: {{ .Release.Name }}
