apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flock-api
spec:
  hosts:
  - "api.flocktory.com"
  gateways:
  - flock-istio-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: flock-api
