apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flock-microservice.fullname" . }}
  labels:
    app: {{ template "flock-microservice.name" . }}
    chart: {{ template "flock-microservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flock-microservice.name" . }}
      track: stable
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flock-microservice.name" . }}
        track: stable
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
#          resources:
#            requests:
#              memory: "64Mi"
#              cpu: "250m"
#            limits:
#              memory: "128Mi"
#              cpu: "500m"
