{{- if .Values.canary.enabled}}
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "flock-microservice.fullname" . }}-canary
  labels:
    app: {{ template "flock-microservice.name" . }}
    chart: {{ template "flock-microservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.canary.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "flock-microservice.name" . }}
      track: canary
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "flock-microservice.name" . }}
        track: canary
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.canary.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
{{- end}}
